// src/utils/foodData.js

export const FOOD_ITEMS = [
  {
    id: 1,
    name: "Classic Smash Burger",
    category: "Burger",
    price: 13.99,
    rating: 4.8,
    reviews: 142,
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=400",
    description: "Double smashed beef patty, melted cheddar, caramelized onions, pickles & signature house special sauce.",
    veg: false,
    spicy: false,
    chefsChoice: true,
  },
  {
    id: 2,
    name: "BBQ Bacon Deluxe",
    category: "Burger",
    price: 15.49,
    rating: 4.9,
    reviews: 98,
    image: "https://images.unsplash.com/photo-1553979459-d2229ba7433b?auto=format&fit=crop&q=80&w=400",
    description: "Crispy applewood bacon, double cheddar, smoky hickory BBQ sauce, and crispy onion rings.",
    veg: false,
    spicy: false,
    chefsChoice: false,
  },
  {
    id: 3,
    name: "Spicy Jalapeño Burger",
    category: "Burger",
    price: 14.99,
    rating: 4.7,
    reviews: 76,
    image: "https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?auto=format&fit=crop&q=80&w=400",
    description: "Spiced beef patty, melted pepper jack cheese, grilled jalapeños, and fiery chipotle mayo.",
    veg: false,
    spicy: true,
    chefsChoice: false,
  },
  {
    id: 4,
    name: "Margherita Classica",
    category: "Pizza",
    price: 16.99,
    rating: 4.9,
    reviews: 184,
    image: "https://images.unsplash.com/photo-1604382355076-af4b0eb60143?auto=format&fit=crop&q=80&w=400",
    description: "Fresh mozzarella, organic basil leaves, signature San Marzano tomato sauce, and cold-pressed olive oil.",
    veg: true,
    spicy: false,
    chefsChoice: true,
  },
  {
    id: 5,
    name: "Spicy Pepperoni Feast",
    category: "Pizza",
    price: 18.49,
    rating: 4.8,
    reviews: 215,
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=400",
    description: "Double pepperoni layers, spicy cup-and-char pepperoni, mozzarella, and a drizzle of hot honey.",
    veg: false,
    spicy: true,
    chefsChoice: false,
  },
  {
    id: 6,
    name: "Truffle Mushroom Garden",
    category: "Pizza",
    price: 19.99,
    rating: 4.6,
    reviews: 58,
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&q=80&w=400",
    description: "Creamy white sauce, wild forest mushrooms, fontina cheese, fresh baby arugula, and truffle oil.",
    veg: true,
    spicy: false,
    chefsChoice: false,
  },
  {
    id: 7,
    name: "Chicken Caesar Wrap",
    category: "Wrap",
    price: 12.49,
    rating: 4.7,
    reviews: 112,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&q=80&w=400",
    description: "Crispy breaded chicken tenders, crunchy romaine lettuce, shaved parmesan, and garlic Caesar dressing.",
    veg: false,
    spicy: false,
    chefsChoice: false,
  },
  {
    id: 8,
    name: "Spicy Mexican Wrap",
    category: "Wrap",
    price: 11.99,
    rating: 4.8,
    reviews: 89,
    image: "https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&q=80&w=400",
    description: "Grilled lime-coriander chicken, black beans, sweet roasted corn, avocado chunks, and chipotle salsa.",
    veg: false,
    spicy: true,
    chefsChoice: false,
  },
  {
    id: 9,
    name: "Vegan Garden Wrap",
    category: "Wrap",
    price: 10.99,
    rating: 4.5,
    reviews: 45,
    image: "https://images.unsplash.com/photo-1551028150-64b9f398f678?auto=format&fit=crop&q=80&w=400",
    description: "Grilled sweet peppers, zucchini, house-made roasted garlic hummus, and fresh organic baby spinach.",
    veg: true,
    spicy: false,
    chefsChoice: false,
  },
  {
    id: 10,
    name: "Molten Lava Chocolate Cake",
    category: "Dessert",
    price: 8.99,
    rating: 4.9,
    reviews: 230,
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&q=80&w=400",
    description: "Warm dark chocolate cake with a gooey liquid chocolate core, served with vanilla bean ice cream.",
    veg: true,
    spicy: false,
    chefsChoice: true,
  },
  {
    id: 11,
    name: "Classic New York Cheesecake",
    category: "Dessert",
    price: 9.49,
    rating: 4.8,
    reviews: 154,
    image: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&q=80&w=400",
    description: "Rich, dense, and creamy traditional cheesecake slice served with homemade sweet strawberry compote.",
    veg: true,
    spicy: false,
    chefsChoice: false,
  },
];
