// src/utils/foodData.js

import classicSmashBurger from "../assets/images/classic_smash_burger.jpg";
import bbqBaconDeluxe from "../assets/images/bbq_bacon_deluxe.jpg";
import spicyJalapenoBurger from "../assets/images/spicy_jalapeno_burger.jpg";
import margheritaClassica from "../assets/images/margherita_classica.jpg";
import spicyPepperoniFeast from "../assets/images/spicy_pepperoni_feast.jpg";
import truffleMushroomGarden from "../assets/images/truffle_mushroom_garden.jpg";
import chickenCaesarWrap from "../assets/images/chicken_caesar_wrap.jpg";
import spicyMexicanWrap from "../assets/images/spicy_mexican_wrap.jpg";
import veganGardenWrap from "../assets/images/vegan_garden_wrap.jpg";
import moltenLavaCake from "../assets/images/molten_lava_cake.jpg";
import newYorkCheesecake from "../assets/images/new_york_cheesecake.jpg";

export const FOOD_ITEMS = [
  {
    id: 1,
    name: "Classic Smash Burger",
    category: "Burger",
    price: 13.99,
    rating: 4.8,
    reviews: 142,
    image: classicSmashBurger,
    description: "Double smashed beef patty, melted cheddar, caramelized onions, pickles & signature house special sauce.",
    veg: false,
    spicy: false,
    chefsChoice: true,
  },
  {
    id: 2,
    name: "BBQ Bacon Deluxe",
    category: "Burger",
    price: 15.49,
    rating: 4.9,
    reviews: 98,
    image: bbqBaconDeluxe,
    description: "Crispy applewood bacon, double cheddar, smoky hickory BBQ sauce, and crispy onion rings.",
    veg: false,
    spicy: false,
    chefsChoice: false,
  },
  {
    id: 3,
    name: "Spicy Jalapeño Burger",
    category: "Burger",
    price: 14.99,
    rating: 4.7,
    reviews: 76,
    image: spicyJalapenoBurger,
    description: "Spiced beef patty, melted pepper jack cheese, grilled jalapeños, and fiery chipotle mayo.",
    veg: false,
    spicy: true,
    chefsChoice: false,
  },
  {
    id: 4,
    name: "Margherita Classica",
    category: "Pizza",
    price: 16.99,
    rating: 4.9,
    reviews: 184,
    image: margheritaClassica,
    description: "Fresh mozzarella, organic basil leaves, signature San Marzano tomato sauce, and cold-pressed olive oil.",
    veg: true,
    spicy: false,
    chefsChoice: true,
  },
  {
    id: 5,
    name: "Spicy Pepperoni Feast",
    category: "Pizza",
    price: 18.49,
    rating: 4.8,
    reviews: 215,
    image: spicyPepperoniFeast,
    description: "Double pepperoni layers, spicy cup-and-char pepperoni, mozzarella, and a drizzle of hot honey.",
    veg: false,
    spicy: true,
    chefsChoice: false,
  },
  {
    id: 6,
    name: "Truffle Mushroom Garden",
    category: "Pizza",
    price: 19.99,
    rating: 4.6,
    reviews: 58,
    image: truffleMushroomGarden,
    description: "Creamy white sauce, wild forest mushrooms, fontina cheese, fresh baby arugula, and truffle oil.",
    veg: true,
    spicy: false,
    chefsChoice: false,
  },
  {
    id: 7,
    name: "Chicken Caesar Wrap",
    category: "Wrap",
    price: 12.49,
    rating: 4.7,
    reviews: 112,
    image: chickenCaesarWrap,
    description: "Crispy breaded chicken tenders, crunchy romaine lettuce, shaved parmesan, and garlic Caesar dressing.",
    veg: false,
    spicy: false,
    chefsChoice: false,
  },
  {
    id: 8,
    name: "Spicy Mexican Wrap",
    category: "Wrap",
    price: 11.99,
    rating: 4.8,
    reviews: 89,
    image: spicyMexicanWrap,
    description: "Grilled lime-coriander chicken, black beans, sweet roasted corn, avocado chunks, and chipotle salsa.",
    veg: false,
    spicy: true,
    chefsChoice: false,
  },
  {
    id: 9,
    name: "Vegan Garden Wrap",
    category: "Wrap",
    price: 10.99,
    rating: 4.5,
    reviews: 45,
    image: veganGardenWrap,
    description: "Grilled sweet peppers, zucchini, house-made roasted garlic hummus, and fresh organic baby spinach.",
    veg: true,
    spicy: false,
    chefsChoice: false,
  },
  {
    id: 10,
    name: "Molten Lava Chocolate Cake",
    category: "Dessert",
    price: 8.99,
    rating: 4.9,
    reviews: 230,
    image: moltenLavaCake,
    description: "Warm dark chocolate cake with a gooey liquid chocolate core, served with vanilla bean ice cream.",
    veg: true,
    spicy: false,
    chefsChoice: true,
  },
  {
    id: 11,
    name: "Classic New York Cheesecake",
    category: "Dessert",
    price: 9.49,
    rating: 4.8,
    reviews: 154,
    image: newYorkCheesecake,
    description: "Rich, dense, and creamy traditional cheesecake slice served with homemade sweet strawberry compote.",
    veg: true,
    spicy: false,
    chefsChoice: false,
  },
];
